channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal =5.2.4
  - python =3.6
  - networkx =2.1
  - matplotlib =2.2.3
  - bcftools =1.9
  - samtools =1.9
  - pysam =0.15.0
  - pandas
  - biopython
  - minimap2
  - racon
  - seqtk
  - kraken2
  - pip:
    - medaka
    - git+https://github.com/SamStudio8/bondage.git
